"use client";

/**
 * Daily Debates Admin - Configure 6 debates per day
 * 
 * Admin interface for:
 * - Adding 6 debates with news URLs (one per category)
 * - Viewing today's debate status
 * - Auto-generation fallback info
 */

import { useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { 
  MessageSquare, Plus, Check, AlertCircle, 
  Shield, Briefcase, Heart, Scale, Cpu, Globe,
  Sparkles, Clock
} from "lucide-react";

const CATEGORIES = [
  { value: "safety", label: "Safety", icon: Shield, color: "var(--color-aurora-mint)" },
  { value: "career", label: "Career", icon: Briefcase, color: "var(--color-aurora-blue)" },
  { value: "health", label: "Health", icon: Heart, color: "var(--color-aurora-pink)" },
  { value: "rights", label: "Rights", icon: Scale, color: "var(--color-aurora-purple)" },
  { value: "tech", label: "Tech", icon: Cpu, color: "var(--color-aurora-yellow)" },
  { value: "world", label: "World", icon: Globe, color: "var(--color-aurora-lavender)" },
] as const;

// Auto-generate button component
function AutoGenerateButton({ date, onSuccess }: { date: string; onSuccess: () => void }) {
  const [isGenerating, setIsGenerating] = useState(false);
  const autoGenerate = useMutation(api.dailyDebates.autoGenerateDebates);

  const handleAutoGenerate = async () => {
    setIsGenerating(true);
    try {
      const result = await autoGenerate({ date, forceRegenerate: true });
      if (result.success) {
        onSuccess();
      }
    } catch (error) {
      console.error("Auto-generate failed:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Button
      onClick={handleAutoGenerate}
      disabled={isGenerating}
      variant="outline"
      className="border-[var(--color-aurora-purple)] text-[var(--color-aurora-purple)] hover:bg-[var(--color-aurora-purple)]/10 min-h-[44px]"
    >
      <Sparkles className="w-4 h-4 mr-2" />
      {isGenerating ? "Generating..." : "Auto-Generate All 6"}
    </Button>
  );
}

export function DailyDebatesAdmin() {
  const [date, setDate] = useState(new Date().toISOString().split("T")[0]);
  const [selectedSlot, setSelectedSlot] = useState(1);
  const [title, setTitle] = useState("");
  const [summary, setSummary] = useState("");
  const [sourceUrl, setSourceUrl] = useState("");
  const [sourceName, setSourceName] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);

  const createDebate = useMutation(api.dailyDebates.createDebate);
  const todayDebates = useQuery(api.dailyDebates.getDebatesByDate, { date });

  const selectedCategory = CATEGORIES[selectedSlot - 1];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title || !summary || !sourceUrl || !sourceName) {
      setMessage({ type: "error", text: "Please fill all required fields" });
      return;
    }

    setIsSubmitting(true);
    setMessage(null);

    try {
      await createDebate({
        date,
        slot: selectedSlot,
        category: selectedCategory.value,
        title,
        summary,
        sourceUrl,
        sourceName,
        imageUrl: imageUrl || undefined,
      });
      setMessage({ type: "success", text: `Debate ${selectedSlot} (${selectedCategory.label}) added!` });
      // Reset form
      setTitle("");
      setSummary("");
      setSourceUrl("");
      setSourceName("");
      setImageUrl("");
      // Move to next empty slot
      const nextEmpty = CATEGORIES.findIndex((_, i) => 
        !todayDebates?.find(d => d.slot === i + 1)
      );
      if (nextEmpty !== -1) setSelectedSlot(nextEmpty + 1);
    } catch (error: any) {
      setMessage({ type: "error", text: error.message || "Failed to add debate" });
    } finally {
      setIsSubmitting(false);
    }
  };

  const filledCount = todayDebates?.length || 0;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[var(--color-aurora-purple)] to-[var(--color-aurora-pink)] flex items-center justify-center">
            <MessageSquare className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-[var(--foreground)]">Daily Debates Admin</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              Configure 6 debates per day for "What Sisters Think"
            </p>
          </div>
        </div>
        <Badge className={filledCount === 6 ? "bg-[var(--color-aurora-mint)]" : "bg-[var(--color-aurora-yellow)]"}>
          {filledCount}/6 configured
        </Badge>
      </div>

      {/* Auto-generation Controls */}
      <Card className="bg-[var(--accent)]/30 border-[var(--border)]">
        <CardContent className="p-4">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-start gap-3">
              <Sparkles className="w-5 h-5 text-[var(--color-aurora-purple)] mt-0.5" />
              <div>
                <p className="font-medium text-[var(--foreground)]">Auto-Generation</p>
                <p className="text-sm text-[var(--muted-foreground)]">
                  Generate all 6 debates automatically with predefined topics. 
                  Topics rotate daily to keep content fresh.
                </p>
              </div>
            </div>
            <AutoGenerateButton date={date} onSuccess={() => {
              setMessage({ type: "success", text: "6 debates auto-generated!" });
            }} />
          </div>
        </CardContent>
      </Card>

      {/* Today's Debates Status */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        {CATEGORIES.map((cat, index) => {
          const slot = index + 1;
          const debate = todayDebates?.find(d => d.slot === slot);
          const Icon = cat.icon;
          
          return (
            <button
              key={cat.value}
              onClick={() => setSelectedSlot(slot)}
              className={`p-3 rounded-xl border transition-all ${
                selectedSlot === slot
                  ? "border-[var(--color-aurora-purple)] bg-[var(--color-aurora-purple)]/10 ring-2 ring-[var(--color-aurora-purple)]"
                  : debate
                  ? "border-[var(--color-aurora-mint)] bg-[var(--color-aurora-mint)]/10"
                  : "border-dashed border-[var(--border)] hover:border-[var(--color-aurora-purple)]/50"
              }`}
            >
              <div className="flex items-center gap-2 mb-2">
                <Icon className="w-4 h-4" style={{ color: cat.color }} />
                <span className="text-xs font-medium">{cat.label}</span>
                {debate && <Check className="w-3 h-3 text-green-500 ml-auto" />}
              </div>
              {debate ? (
                <p className="text-xs text-[var(--foreground)] line-clamp-2 text-left">
                  {debate.title}
                </p>
              ) : (
                <p className="text-xs text-[var(--muted-foreground)]">Empty</p>
              )}
              {debate?.isAutoGenerated && (
                <Badge variant="outline" className="mt-1 text-xs">Auto</Badge>
              )}
            </button>
          );
        })}
      </div>

      {/* Add Debate Form */}
      <Card className="bg-[var(--card)] border-[var(--border)]">
        <CardHeader className="pb-3">
          <CardTitle className="text-lg flex items-center gap-2">
            <selectedCategory.icon className="w-5 h-5" style={{ color: selectedCategory.color }} />
            Add {selectedCategory.label} Debate (Slot {selectedSlot})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-[var(--foreground)] mb-1">
                  Date
                </label>
                <input
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  className="w-full h-10 px-3 rounded-lg bg-[var(--accent)] border border-[var(--border)] text-[var(--foreground)]"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-[var(--foreground)] mb-1">
                  Category
                </label>
                <div 
                  className="h-10 px-3 rounded-lg bg-[var(--accent)] border border-[var(--border)] flex items-center gap-2"
                  style={{ borderColor: selectedCategory.color }}
                >
                  <selectedCategory.icon className="w-4 h-4" style={{ color: selectedCategory.color }} />
                  <span>{selectedCategory.label}</span>
                </div>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-[var(--foreground)] mb-1">
                Title *
              </label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Debate headline..."
                className="w-full h-10 px-3 rounded-lg bg-[var(--accent)] border border-[var(--border)] text-[var(--foreground)]"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-[var(--foreground)] mb-1">
                Summary *
              </label>
              <textarea
                value={summary}
                onChange={(e) => setSummary(e.target.value)}
                placeholder="Brief summary for display..."
                className="w-full p-3 rounded-lg bg-[var(--accent)] border border-[var(--border)] text-[var(--foreground)] resize-none h-20"
                required
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-[var(--foreground)] mb-1">
                  Source Name *
                </label>
                <input
                  type="text"
                  value={sourceName}
                  onChange={(e) => setSourceName(e.target.value)}
                  placeholder="BBC, Reuters, etc."
                  className="w-full h-10 px-3 rounded-lg bg-[var(--accent)] border border-[var(--border)] text-[var(--foreground)]"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-[var(--foreground)] mb-1">
                  Source URL *
                </label>
                <input
                  type="url"
                  value={sourceUrl}
                  onChange={(e) => setSourceUrl(e.target.value)}
                  placeholder="https://..."
                  className="w-full h-10 px-3 rounded-lg bg-[var(--accent)] border border-[var(--border)] text-[var(--foreground)]"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-[var(--foreground)] mb-1">
                Image URL (optional)
              </label>
              <input
                type="url"
                value={imageUrl}
                onChange={(e) => setImageUrl(e.target.value)}
                placeholder="https://... (optional thumbnail)"
                className="w-full h-10 px-3 rounded-lg bg-[var(--accent)] border border-[var(--border)] text-[var(--foreground)]"
              />
            </div>

            {message && (
              <div
                className={`p-3 rounded-lg flex items-center gap-2 ${
                  message.type === "success"
                    ? "bg-[var(--color-aurora-mint)]/20 text-green-700"
                    : "bg-[var(--color-aurora-salmon)]/20 text-red-700"
                }`}
              >
                {message.type === "success" ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <AlertCircle className="w-4 h-4" />
                )}
                {message.text}
              </div>
            )}

            <Button
              type="submit"
              disabled={isSubmitting}
              className="w-full bg-[var(--color-aurora-purple)] min-h-[48px]"
            >
              <Plus className="w-4 h-4 mr-2" />
              {isSubmitting ? "Adding..." : `Add ${selectedCategory.label} Debate`}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
