import { v } from "convex/values";
import { query, mutation } from "./_generated/server";

// Categories for daily debates
const DEBATE_CATEGORIES = [
  "safety",
  "career", 
  "health",
  "rights",
  "tech",
  "world",
] as const;

/**
 * Get today's 6 debates
 */
export const getTodayDebates = query({
  args: {},
  handler: async (ctx) => {
    const today = new Date().toISOString().split("T")[0];
    const debates = await ctx.db
      .query("dailyDebates")
      .withIndex("by_date", (q) => q.eq("date", today))
      .filter((q) => q.eq(q.field("isActive"), true))
      .collect();
    
    return debates.sort((a, b) => a.slot - b.slot);
  },
});

/**
 * Get debates by specific date
 */
export const getDebatesByDate = query({
  args: { date: v.string() },
  handler: async (ctx, args) => {
    const debates = await ctx.db
      .query("dailyDebates")
      .withIndex("by_date", (q) => q.eq("date", args.date))
      .collect();
    
    return debates.sort((a, b) => a.slot - b.slot);
  },
});

/**
 * Create a debate (admin only)
 */
export const createDebate = mutation({
  args: {
    date: v.string(),
    slot: v.number(),
    category: v.union(
      v.literal("safety"),
      v.literal("career"),
      v.literal("health"),
      v.literal("rights"),
      v.literal("tech"),
      v.literal("world")
    ),
    title: v.string(),
    summary: v.string(),
    sourceUrl: v.string(),
    sourceName: v.string(),
    imageUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // Check if slot already exists for this date
    const existing = await ctx.db
      .query("dailyDebates")
      .withIndex("by_date_slot", (q) => 
        q.eq("date", args.date).eq("slot", args.slot)
      )
      .first();
    
    if (existing) {
      // Update existing debate
      await ctx.db.patch(existing._id, {
        category: args.category,
        title: args.title,
        summary: args.summary,
        sourceUrl: args.sourceUrl,
        sourceName: args.sourceName,
        imageUrl: args.imageUrl,
        isAutoGenerated: false,
      });
      return existing._id;
    }
    
    // Create new debate
    return await ctx.db.insert("dailyDebates", {
      date: args.date,
      slot: args.slot,
      category: args.category,
      title: args.title,
      summary: args.summary,
      sourceUrl: args.sourceUrl,
      sourceName: args.sourceName,
      imageUrl: args.imageUrl,
      agreeCount: 0,
      disagreeCount: 0,
      neutralCount: 0,
      commentCount: 0,
      isAutoGenerated: false,
      isActive: true,
    });
  },
});


/**
 * Vote on a debate
 */
export const voteOnDebate = mutation({
  args: {
    debateId: v.id("dailyDebates"),
    vote: v.union(v.literal("agree"), v.literal("disagree"), v.literal("neutral")),
    // Anonymous voting
    sessionHash: v.optional(v.string()),
    anonymousId: v.optional(v.id("anonymousDebaters")),
    // Member voting
    memberId: v.optional(v.id("users")),
  },
  handler: async (ctx, args) => {
    const debate = await ctx.db.get(args.debateId);
    if (!debate) throw new Error("Debate not found");

    const voterType = args.memberId ? "member" : "anonymous";
    
    // Check for existing vote
    let existingVote = null;
    if (args.memberId) {
      existingVote = await ctx.db
        .query("debateVotes")
        .withIndex("by_member_debate", (q) => 
          q.eq("memberId", args.memberId).eq("debateId", args.debateId)
        )
        .first();
    } else if (args.anonymousId) {
      existingVote = await ctx.db
        .query("debateVotes")
        .withIndex("by_anonymous_debate", (q) => 
          q.eq("anonymousId", args.anonymousId).eq("debateId", args.debateId)
        )
        .first();
    }

    // Update vote counts
    const updates: Record<string, number> = {};
    
    if (existingVote) {
      // Remove old vote count
      if (existingVote.vote === "agree") updates.agreeCount = debate.agreeCount - 1;
      else if (existingVote.vote === "disagree") updates.disagreeCount = debate.disagreeCount - 1;
      else updates.neutralCount = debate.neutralCount - 1;
      
      // Update existing vote
      await ctx.db.patch(existingVote._id, { vote: args.vote, timestamp: Date.now() });
    } else {
      // Create new vote
      await ctx.db.insert("debateVotes", {
        debateId: args.debateId,
        voterType,
        anonymousId: args.anonymousId,
        memberId: args.memberId,
        vote: args.vote,
        timestamp: Date.now(),
      });
    }

    // Add new vote count
    if (args.vote === "agree") updates.agreeCount = (updates.agreeCount ?? debate.agreeCount) + 1;
    else if (args.vote === "disagree") updates.disagreeCount = (updates.disagreeCount ?? debate.disagreeCount) + 1;
    else updates.neutralCount = (updates.neutralCount ?? debate.neutralCount) + 1;

    await ctx.db.patch(args.debateId, updates);

    // Only award credits to REGISTERED users (not anonymous)
    // Anonymous users get gamified messages but no real credits
    if (args.memberId && !existingVote) {
      const user = await ctx.db.get(args.memberId);
      if (user) {
        await ctx.db.patch(args.memberId, {
          credits: (user.credits || 0) + 2,
        });
        return { success: true, creditsAwarded: 2, isRegistered: true };
      }
    }

    // For anonymous users - return gamified response without storing credits
    return { 
      success: true, 
      creditsAwarded: 0, 
      isRegistered: false,
      message: "Your voice matters! Join Aurora App to earn credits and save your history."
    };
  },
});

/**
 * Add a comment to a debate
 */
export const addComment = mutation({
  args: {
    debateId: v.id("dailyDebates"),
    content: v.string(),
    parentId: v.optional(v.id("debateComments")),
    // Anonymous
    anonymousId: v.optional(v.id("anonymousDebaters")),
    // Member
    memberId: v.optional(v.id("users")),
  },
  handler: async (ctx, args) => {
    const debate = await ctx.db.get(args.debateId);
    if (!debate) throw new Error("Debate not found");

    const authorType = args.memberId ? "member" : "anonymous";

    const commentId = await ctx.db.insert("debateComments", {
      debateId: args.debateId,
      authorType,
      anonymousId: args.anonymousId,
      memberId: args.memberId,
      content: args.content,
      upvotes: 0,
      downvotes: 0,
      replyCount: 0,
      parentId: args.parentId,
      isHidden: false,
    });

    // Update debate comment count
    await ctx.db.patch(args.debateId, {
      commentCount: debate.commentCount + 1,
    });

    // Update parent reply count if this is a reply
    if (args.parentId) {
      const parent = await ctx.db.get(args.parentId);
      if (parent) {
        await ctx.db.patch(args.parentId, {
          replyCount: parent.replyCount + 1,
        });
      }
    }

    // Only award credits to REGISTERED users (not anonymous)
    // Anonymous users get gamified messages but no real credits
    if (args.memberId) {
      const user = await ctx.db.get(args.memberId);
      if (user) {
        await ctx.db.patch(args.memberId, {
          credits: (user.credits || 0) + 3,
        });
        return { commentId, creditsAwarded: 3, isRegistered: true };
      }
    }

    // For anonymous users - return gamified response
    return { 
      commentId, 
      creditsAwarded: 0, 
      isRegistered: false,
      message: "Great insight! Join Aurora App to earn 3 credits for every comment."
    };
  },
});

/**
 * Get comments for a debate
 */
export const getDebateComments = query({
  args: { debateId: v.id("dailyDebates") },
  handler: async (ctx, args) => {
    const comments = await ctx.db
      .query("debateComments")
      .withIndex("by_debate", (q) => q.eq("debateId", args.debateId))
      .filter((q) => q.eq(q.field("isHidden"), false))
      .collect();

    // Enrich with author info
    const enrichedComments = await Promise.all(
      comments.map(async (comment) => {
        let authorName = "Anonymous";
        let authorFlag = "🌍";
        let authorBadge = null;

        if (comment.authorType === "member" && comment.memberId) {
          const member = await ctx.db.get(comment.memberId);
          if (member) {
            authorName = member.name;
            authorFlag = ""; // Members don't show flag
            authorBadge = member.isPremium ? "premium" : null;
          }
        } else if (comment.anonymousId) {
          const anon = await ctx.db.get(comment.anonymousId);
          if (anon) {
            authorName = anon.pseudonym;
            authorFlag = anon.countryFlag;
          }
        }

        return {
          ...comment,
          authorName,
          authorFlag,
          authorBadge,
        };
      })
    );

    return enrichedComments;
  },
});

/**
 * Get vote distribution for a debate
 */
export const getVoteDistribution = query({
  args: { debateId: v.id("dailyDebates") },
  handler: async (ctx, args) => {
    const debate = await ctx.db.get(args.debateId);
    if (!debate) return null;

    const total = debate.agreeCount + debate.disagreeCount + debate.neutralCount;
    
    return {
      agree: debate.agreeCount,
      disagree: debate.disagreeCount,
      neutral: debate.neutralCount,
      total,
      agreePercent: total > 0 ? Math.round((debate.agreeCount / total) * 100) : 0,
      disagreePercent: total > 0 ? Math.round((debate.disagreeCount / total) * 100) : 0,
      neutralPercent: total > 0 ? Math.round((debate.neutralCount / total) * 100) : 0,
    };
  },
});


/**
 * Check if debates exist for a given date
 */
export const hasDebatesForDate = query({
  args: { date: v.string() },
  handler: async (ctx, args) => {
    const debates = await ctx.db
      .query("dailyDebates")
      .withIndex("by_date", (q) => q.eq("date", args.date))
      .collect();
    
    return {
      hasDebates: debates.length > 0,
      count: debates.length,
      isComplete: debates.length >= 6,
    };
  },
});

/**
 * Auto-generate debates for today if none exist
 * This can be called by a scheduled function or manually by admin
 * Uses predefined topics when Search API is not available
 */
export const autoGenerateDebates = mutation({
  args: {
    date: v.optional(v.string()),
    forceRegenerate: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const targetDate = args.date || new Date().toISOString().split("T")[0];
    
    // Check if debates already exist
    const existing = await ctx.db
      .query("dailyDebates")
      .withIndex("by_date", (q) => q.eq("date", targetDate))
      .collect();
    
    if (existing.length >= 6 && !args.forceRegenerate) {
      return { success: false, message: "Debates already exist for this date", count: existing.length };
    }

    // If force regenerate, deactivate existing debates
    if (args.forceRegenerate && existing.length > 0) {
      for (const debate of existing) {
        await ctx.db.patch(debate._id, { isActive: false });
      }
    }

    // Expanded debate topics by category - 30+ topics per category for variety
    // Topics rotate daily based on day of year for fresh content
    const debateTopics = {
      safety: [
        { title: "Should women share their location with trusted contacts at all times?", summary: "Discussing the balance between safety and privacy in location sharing." },
        { title: "Are ride-sharing apps doing enough to protect women passengers?", summary: "Evaluating safety measures in transportation services." },
        { title: "Should self-defense training be mandatory in schools for girls?", summary: "Debating the role of education in women's safety." },
        { title: "Is walking alone at night ever truly safe for women?", summary: "Examining urban safety and women's freedom of movement." },
        { title: "Should there be women-only public transportation options?", summary: "Discussing gender-segregated transit solutions." },
        { title: "Are dating apps doing enough to verify user identities?", summary: "Examining safety measures in online dating platforms." },
        { title: "Should pepper spray be legal everywhere for women?", summary: "Debating self-defense tools and legal restrictions." },
        { title: "Are workplace parking lots safe enough for women?", summary: "Discussing employer responsibility for employee safety." },
        { title: "Should hotels have women-only floors?", summary: "Examining gender-specific accommodations for safety." },
        { title: "Is street harassment a serious enough crime?", summary: "Debating legal consequences for catcalling and harassment." },
        { title: "Should there be panic buttons in all public restrooms?", summary: "Discussing emergency response infrastructure." },
        { title: "Are college campuses doing enough to prevent assault?", summary: "Examining campus safety policies and enforcement." },
        { title: "Should women have access to free safety apps?", summary: "Debating public funding for personal safety technology." },
        { title: "Is victim-blaming still a problem in safety discussions?", summary: "Examining how society discusses women's safety." },
        { title: "Should there be more female police officers?", summary: "Discussing gender representation in law enforcement." },
        { title: "Are emergency services responsive enough to women's calls?", summary: "Examining response times and treatment of female callers." },
        { title: "Should gyms have women-only hours?", summary: "Debating gender-specific access to fitness facilities." },
        { title: "Is online stalking taken seriously enough by authorities?", summary: "Examining legal responses to digital harassment." },
        { title: "Should there be safety ratings for neighborhoods?", summary: "Discussing public information about area safety." },
        { title: "Are women safe enough in co-working spaces?", summary: "Examining safety in modern work environments." },
        { title: "Should delivery drivers be verified for women's safety?", summary: "Debating background checks for service workers." },
        { title: "Is public lighting adequate for women's safety?", summary: "Discussing urban infrastructure and safety." },
        { title: "Should there be women-only beaches or pools?", summary: "Examining gender-segregated recreational spaces." },
        { title: "Are music festivals safe enough for women?", summary: "Discussing safety at large public events." },
        { title: "Should bars be required to train staff on drink spiking?", summary: "Examining hospitality industry safety standards." },
        { title: "Is it safe for women to travel solo internationally?", summary: "Debating global safety for female travelers." },
        { title: "Should there be more female security guards?", summary: "Discussing gender diversity in security services." },
        { title: "Are smart home devices making women safer or more vulnerable?", summary: "Examining technology's dual role in safety." },
        { title: "Should there be mandatory safety escorts on campuses?", summary: "Debating institutional safety services." },
        { title: "Is the 'buddy system' still relevant for women's safety?", summary: "Examining traditional safety practices in modern times." },
      ],
      career: [
        { title: "Should companies be required to publish gender pay gap data?", summary: "Transparency in workplace compensation practices." },
        { title: "Is remote work better for women's career advancement?", summary: "Examining the impact of flexible work on women's careers." },
        { title: "Should there be quotas for women in leadership positions?", summary: "Debating affirmative action in corporate leadership." },
        { title: "Are women penalized for negotiating salaries?", summary: "Discussing gender dynamics in salary negotiations." },
        { title: "Should parental leave be equal for all genders?", summary: "Examining the impact of leave policies on women's careers." },
        { title: "Is the 'glass ceiling' still a real barrier?", summary: "Debating invisible barriers to women's advancement." },
        { title: "Should companies offer egg freezing as a benefit?", summary: "Examining fertility benefits and career planning." },
        { title: "Are women judged more harshly in performance reviews?", summary: "Discussing bias in workplace evaluations." },
        { title: "Should networking events be more inclusive for women?", summary: "Examining professional networking culture." },
        { title: "Is entrepreneurship easier or harder for women?", summary: "Debating gender dynamics in starting businesses." },
        { title: "Should there be more women-only professional networks?", summary: "Discussing gender-specific career support." },
        { title: "Are women expected to do more 'office housework'?", summary: "Examining invisible labor in the workplace." },
        { title: "Should companies have mandatory mentorship for women?", summary: "Debating structured career development programs." },
        { title: "Is the 'mommy track' still a career killer?", summary: "Discussing career impacts of motherhood." },
        { title: "Should job postings be required to show salary ranges?",  summary: "Examining pay transparency in hiring." },
        { title: "Are women in male-dominated fields treated fairly?", summary: "Discussing experiences in STEM, finance, etc." },
        { title: "Should there be returnship programs for career breaks?", summary: "Examining re-entry support for women." },
        { title: "Is imposter syndrome more common in women?", summary: "Debating confidence gaps in professional settings." },
        { title: "Should companies track promotion rates by gender?", summary: "Discussing accountability in career advancement." },
        { title: "Are women's leadership styles undervalued?", summary: "Examining different approaches to leadership." },
        { title: "Should there be more women in venture capital?", summary: "Discussing funding access for female founders." },
        { title: "Is the gig economy good or bad for women?", summary: "Examining flexible work and job security." },
        { title: "Should companies offer childcare subsidies?", summary: "Debating employer support for working parents." },
        { title: "Are women's professional achievements celebrated equally?", summary: "Discussing recognition and visibility." },
        { title: "Should there be blind hiring processes?", summary: "Examining bias reduction in recruitment." },
        { title: "Is work-life balance a women's issue?", summary: "Debating gendered expectations around balance." },
        { title: "Should companies have diversity officers?", summary: "Discussing institutional commitment to inclusion." },
        { title: "Are women's voices heard in meetings?", summary: "Examining speaking dynamics in professional settings." },
        { title: "Should there be more women on corporate boards?", summary: "Debating governance and representation." },
        { title: "Is freelancing empowering or precarious for women?", summary: "Examining independent work arrangements." },
      ],
      health: [
        { title: "Is women's health research adequately funded?", summary: "Discussing gender disparities in medical research." },
        { title: "Should menstrual products be free for all women?", summary: "Debating period poverty and access to hygiene products." },
        { title: "Are women's pain symptoms taken seriously by doctors?", summary: "Examining gender bias in healthcare." },
        { title: "Should mental health days be a workplace right?", summary: "Discussing mental health support for working women." },
        { title: "Is the beauty industry harmful to women's self-image?", summary: "Examining beauty standards and mental health." },
        { title: "Should birth control be free and accessible everywhere?", summary: "Debating reproductive healthcare access." },
        { title: "Are eating disorders adequately addressed in healthcare?", summary: "Examining treatment for body image issues." },
        { title: "Should there be more female doctors?", summary: "Discussing gender representation in medicine." },
        { title: "Is postpartum depression taken seriously enough?", summary: "Examining maternal mental health support." },
        { title: "Should menopause be discussed more openly?", summary: "Debating stigma around women's health stages." },
        { title: "Are women over-prescribed medication?", summary: "Examining gender bias in prescribing practices." },
        { title: "Should fertility treatments be covered by insurance?", summary: "Discussing reproductive healthcare costs." },
        { title: "Is endometriosis diagnosed quickly enough?", summary: "Examining delays in women's health diagnoses." },
        { title: "Should there be more research on PCOS?", summary: "Debating funding for common women's conditions." },
        { title: "Are women's heart attack symptoms well-known?", summary: "Discussing gender differences in health education." },
        { title: "Should breast cancer screening start earlier?", summary: "Examining preventive care guidelines." },
        { title: "Is maternal mortality a crisis in developed countries?", summary: "Debating childbirth safety standards." },
        { title: "Should HPV vaccines be mandatory?", summary: "Discussing preventive healthcare policies." },
        { title: "Are women's sports injuries treated differently?", summary: "Examining gender bias in sports medicine." },
        { title: "Should there be more research on autoimmune diseases?", summary: "Debating funding for conditions affecting women." },
        { title: "Is anxiety more common in women or just diagnosed more?", summary: "Examining mental health gender patterns." },
        { title: "Should there be women-only gyms for health reasons?", summary: "Discussing comfortable fitness environments." },
        { title: "Are women's nutritional needs different?", summary: "Examining gender-specific dietary guidance." },
        { title: "Should there be more female-focused health apps?", summary: "Debating technology in women's health." },
        { title: "Is chronic fatigue in women taken seriously?", summary: "Discussing dismissal of women's symptoms." },
        { title: "Should there be better support for miscarriage?", summary: "Examining emotional and medical care." },
        { title: "Are women's sleep issues adequately studied?", summary: "Debating research on gender and sleep." },
        { title: "Should there be more awareness about PMDD?", summary: "Discussing severe premenstrual conditions." },
        { title: "Is women's bone health prioritized enough?", summary: "Examining osteoporosis prevention." },
        { title: "Should there be better menstrual leave policies?", summary: "Debating workplace accommodations for periods." },
      ],
      rights: [
        { title: "Should online harassment of women carry stricter penalties?", summary: "Discussing legal protections against cyber abuse." },
        { title: "Are current domestic violence laws adequate?", summary: "Examining legal protections for abuse survivors." },
        { title: "Should there be a global standard for women's rights?", summary: "Debating international women's rights frameworks." },
        { title: "Is the gender gap in STEM fields closing fast enough?", summary: "Discussing progress in gender equality in technology." },
        { title: "Should childcare be a universal right?", summary: "Examining childcare policies and women's economic participation." },
        { title: "Is reproductive choice a fundamental right?", summary: "Debating bodily autonomy and healthcare access." },
        { title: "Should marital rape be criminalized everywhere?", summary: "Examining legal gaps in domestic abuse laws." },
        { title: "Are women's property rights protected globally?", summary: "Discussing economic rights and inheritance." },
        { title: "Should there be gender quotas in politics?", summary: "Debating representation in government." },
        { title: "Is forced marriage still a global problem?", summary: "Examining child marriage and consent laws." },
        { title: "Should there be stronger laws against FGM?", summary: "Discussing protection from harmful practices." },
        { title: "Are women's voices heard in constitutional reforms?", summary: "Examining participation in legal changes." },
        { title: "Should there be equal inheritance rights?", summary: "Debating gender equality in family law." },
        { title: "Is access to education a women's rights issue?", summary: "Discussing barriers to girls' education." },
        { title: "Should there be stronger anti-discrimination laws?", summary: "Examining workplace and social protections." },
        { title: "Are women refugees protected adequately?", summary: "Debating gender-specific asylum policies." },
        { title: "Should there be laws against period shaming?", summary: "Discussing menstrual stigma and rights." },
        { title: "Is economic independence a women's right?", summary: "Examining financial autonomy and access." },
        { title: "Should there be stronger laws against trafficking?", summary: "Debating protection from exploitation." },
        { title: "Are women's land rights protected in rural areas?", summary: "Discussing agricultural and property rights." },
        { title: "Should there be gender-responsive budgeting?", summary: "Examining government spending and women." },
        { title: "Is access to justice equal for women?", summary: "Debating legal system accessibility." },
        { title: "Should there be stronger workplace harassment laws?", summary: "Discussing professional environment protections." },
        { title: "Are women's political rights advancing globally?", summary: "Examining voting and participation rights." },
        { title: "Should there be laws protecting pregnant workers?", summary: "Debating maternity discrimination." },
        { title: "Is digital privacy a women's rights issue?", summary: "Discussing online safety and consent." },
        { title: "Should there be stronger revenge porn laws?", summary: "Examining non-consensual image sharing." },
        { title: "Are women's health rights being rolled back?", summary: "Debating recent policy changes." },
        { title: "Should there be gender impact assessments for laws?", summary: "Discussing policy evaluation processes." },
        { title: "Is freedom of dress a women's right?", summary: "Examining clothing restrictions and autonomy." },
      ],
      tech: [
        { title: "Is AI perpetuating gender bias in hiring?", summary: "Examining algorithmic bias in recruitment technology." },
        { title: "Should social media platforms do more to protect women?", summary: "Discussing platform responsibility for user safety." },
        { title: "Are women adequately represented in tech leadership?", summary: "Examining gender diversity in technology companies." },
        { title: "Is the metaverse safe for women?", summary: "Discussing safety concerns in virtual reality spaces." },
        { title: "Should there be more women-focused tech products?", summary: "Examining the gender gap in product design." },
        { title: "Is facial recognition technology biased against women?", summary: "Debating accuracy and fairness in AI systems." },
        { title: "Should coding be taught differently to girls?", summary: "Examining gender-inclusive tech education." },
        { title: "Are women's health apps protecting user data?", summary: "Discussing privacy in femtech applications." },
        { title: "Is the tech bro culture changing?", summary: "Examining workplace culture in Silicon Valley." },
        { title: "Should there be more women in cybersecurity?", summary: "Debating gender diversity in security fields." },
        { title: "Are voice assistants reinforcing gender stereotypes?", summary: "Examining AI personality design choices." },
        { title: "Should there be women-only coding bootcamps?", summary: "Discussing gender-specific tech training." },
        { title: "Is online gaming hostile to women?", summary: "Examining harassment in gaming communities." },
        { title: "Should there be more women in AI development?", summary: "Debating diversity in artificial intelligence." },
        { title: "Are dating app algorithms fair to women?", summary: "Examining bias in matching systems." },
        { title: "Should there be better tools to detect deepfakes?", summary: "Discussing protection from synthetic media." },
        { title: "Is cryptocurrency accessible to women?", summary: "Examining gender gaps in blockchain adoption." },
        { title: "Should there be more women tech founders?", summary: "Debating entrepreneurship in technology." },
        { title: "Are smart home devices designed with women in mind?", summary: "Examining product design inclusivity." },
        { title: "Should there be women-focused tech investment funds?", summary: "Discussing funding for female founders." },
        { title: "Is remote work technology helping or hurting women?", summary: "Examining digital tools and work-life balance." },
        { title: "Should there be more women in robotics?", summary: "Debating diversity in automation fields." },
        { title: "Are period tracking apps trustworthy?", summary: "Discussing data privacy in health apps." },
        { title: "Should there be better online harassment reporting tools?", summary: "Examining platform safety features." },
        { title: "Is the digital divide affecting women more?", summary: "Debating technology access and gender." },
        { title: "Should there be more women in quantum computing?", summary: "Discussing diversity in emerging tech." },
        { title: "Are wearable devices designed for women's bodies?", summary: "Examining product fit and functionality." },
        { title: "Should there be women-led tech policy making?", summary: "Debating representation in tech regulation." },
        { title: "Is telemedicine improving women's healthcare access?", summary: "Examining digital health services." },
        { title: "Should there be more women in tech journalism?", summary: "Discussing media representation in tech." },
      ],
      world: [
        { title: "Is climate change affecting women disproportionately?", summary: "Examining the gendered impact of environmental change." },
        { title: "Should more countries have women leaders?", summary: "Discussing gender representation in global politics." },
        { title: "Are women's voices heard in peace negotiations?", summary: "Examining women's role in conflict resolution." },
        { title: "Is education the key to women's empowerment globally?", summary: "Discussing the impact of education on women's rights." },
        { title: "Should there be a global minimum wage for women?", summary: "Examining economic policies for gender equality." },
        { title: "Is the UN doing enough for women's rights?", summary: "Debating international organization effectiveness." },
        { title: "Are women refugees treated fairly?", summary: "Examining gender-specific challenges in displacement." },
        { title: "Should there be more women in diplomacy?", summary: "Discussing gender representation in foreign affairs." },
        { title: "Is microfinance empowering women globally?", summary: "Examining small loans and economic independence." },
        { title: "Should there be global standards for maternity leave?", summary: "Debating international workplace policies." },
        { title: "Are women farmers supported adequately?", summary: "Discussing agricultural policies and gender." },
        { title: "Should there be more women in humanitarian work?", summary: "Examining gender in aid organizations." },
        { title: "Is child marriage declining fast enough globally?", summary: "Debating progress on ending early marriage." },
        { title: "Should there be more women in international courts?", summary: "Discussing judicial representation." },
        { title: "Are women's cooperatives effective for development?", summary: "Examining collective economic models." },
        { title: "Should there be gender quotas in international bodies?", summary: "Debating representation in global governance." },
        { title: "Is maternal health improving globally?", summary: "Examining progress in childbirth safety." },
        { title: "Should there be more women peacekeepers?", summary: "Discussing gender in military operations." },
        { title: "Are women's NGOs adequately funded?", summary: "Examining support for women's organizations." },
        { title: "Should there be global standards for domestic violence?", summary: "Debating international legal frameworks." },
        { title: "Is girls' education a global priority?", summary: "Discussing investment in female education." },
        { title: "Should there be more women in climate negotiations?", summary: "Examining gender in environmental policy." },
        { title: "Are women's land rights improving globally?", summary: "Debating property ownership progress." },
        { title: "Should there be global standards for workplace harassment?", summary: "Discussing international labor protections." },
        { title: "Is women's political participation increasing worldwide?", summary: "Examining voting and representation trends." },
        { title: "Should there be more women in global health leadership?", summary: "Debating WHO and health organization diversity." },
        { title: "Are women's economic rights advancing globally?", summary: "Examining financial inclusion progress." },
        { title: "Should there be global standards for reproductive rights?", summary: "Discussing international health policies." },
        { title: "Is gender-based violence decreasing worldwide?", summary: "Examining global safety trends." },
        { title: "Should there be more women in tech policy globally?", summary: "Debating digital governance representation." },
      ],
    };

    // Get day of year to rotate topics
    const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000);
    
    const categories = ["safety", "career", "health", "rights", "tech", "world"] as const;
    const createdDebates = [];

    for (let slot = 1; slot <= 6; slot++) {
      const category = categories[slot - 1];
      const topics = debateTopics[category];
      const topicIndex = dayOfYear % topics.length;
      const topic = topics[topicIndex];

      const debateId = await ctx.db.insert("dailyDebates", {
        date: targetDate,
        slot,
        category,
        title: topic.title,
        summary: topic.summary,
        sourceUrl: "https://miaurora.app",
        sourceName: "Aurora App Community",
        agreeCount: 0,
        disagreeCount: 0,
        neutralCount: 0,
        commentCount: 0,
        isAutoGenerated: true,
        isActive: true,
      });

      createdDebates.push(debateId);
    }

    return { 
      success: true, 
      message: `Created ${createdDebates.length} debates for ${targetDate}`,
      count: createdDebates.length,
      debateIds: createdDebates,
    };
  },
});

/**
 * Delete all debates for a date (admin only)
 */
export const deleteDebatesForDate = mutation({
  args: { date: v.string() },
  handler: async (ctx, args) => {
    const debates = await ctx.db
      .query("dailyDebates")
      .withIndex("by_date", (q) => q.eq("date", args.date))
      .collect();
    
    for (const debate of debates) {
      await ctx.db.delete(debate._id);
    }

    return { success: true, deleted: debates.length };
  },
});


// ============================================
// ADMIN MONITORING & ANALYTICS
// ============================================

/**
 * Get debate analytics for admin dashboard
 */
export const getDebateAnalytics = query({
  args: { date: v.optional(v.string()) },
  handler: async (ctx, args) => {
    const targetDate = args.date || new Date().toISOString().split("T")[0];
    
    const debates = await ctx.db
      .query("dailyDebates")
      .withIndex("by_date", (q) => q.eq("date", targetDate))
      .collect();

    // Get all votes for these debates
    const debateIds = debates.map(d => d._id);
    const allVotes = await Promise.all(
      debateIds.map(async (debateId) => {
        const votes = await ctx.db
          .query("debateVotes")
          .withIndex("by_debate", (q) => q.eq("debateId", debateId))
          .collect();
        return { debateId, votes };
      })
    );

    // Get all comments for these debates
    const allComments = await Promise.all(
      debateIds.map(async (debateId) => {
        const comments = await ctx.db
          .query("debateComments")
          .withIndex("by_debate", (q) => q.eq("debateId", debateId))
          .collect();
        return { debateId, comments };
      })
    );

    // Calculate analytics
    const analytics = debates.map((debate) => {
      const debateVotes = allVotes.find(v => v.debateId === debate._id)?.votes || [];
      const debateComments = allComments.find(c => c.debateId === debate._id)?.comments || [];
      
      const memberVotes = debateVotes.filter(v => v.voterType === "member").length;
      const anonymousVotes = debateVotes.filter(v => v.voterType === "anonymous").length;
      const memberComments = debateComments.filter(c => c.authorType === "member").length;
      const anonymousComments = debateComments.filter(c => c.authorType === "anonymous").length;

      return {
        ...debate,
        totalVotes: debate.agreeCount + debate.disagreeCount + debate.neutralCount,
        memberVotes,
        anonymousVotes,
        memberComments,
        anonymousComments,
        engagementScore: (debate.agreeCount + debate.disagreeCount + debate.neutralCount) + (debate.commentCount * 2),
        conversionPotential: anonymousVotes + anonymousComments, // Users who could convert
      };
    });

    // Summary stats
    const totalVotes = analytics.reduce((sum, d) => sum + d.totalVotes, 0);
    const totalComments = analytics.reduce((sum, d) => sum + d.commentCount, 0);
    const totalMemberEngagement = analytics.reduce((sum, d) => sum + d.memberVotes + d.memberComments, 0);
    const totalAnonymousEngagement = analytics.reduce((sum, d) => sum + d.anonymousVotes + d.anonymousComments, 0);

    return {
      date: targetDate,
      debates: analytics.sort((a, b) => b.engagementScore - a.engagementScore),
      summary: {
        totalDebates: debates.length,
        totalVotes,
        totalComments,
        totalMemberEngagement,
        totalAnonymousEngagement,
        conversionOpportunity: totalAnonymousEngagement,
        avgEngagementPerDebate: debates.length > 0 ? Math.round((totalVotes + totalComments) / debates.length) : 0,
      },
    };
  },
});

/**
 * Get archived debates (historical data)
 */
export const getArchivedDebates = query({
  args: { 
    startDate: v.optional(v.string()),
    endDate: v.optional(v.string()),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const today = new Date().toISOString().split("T")[0];
    const endDate = args.endDate || today;
    const limit = args.limit || 30;

    // Get all debates, sorted by date descending
    let debates = await ctx.db
      .query("dailyDebates")
      .order("desc")
      .collect();

    // Filter by date range
    debates = debates.filter(d => {
      if (args.startDate && d.date < args.startDate) return false;
      if (d.date > endDate) return false;
      return true;
    });

    // Group by date
    const groupedByDate: Record<string, typeof debates> = {};
    for (const debate of debates.slice(0, limit * 6)) {
      if (!groupedByDate[debate.date]) {
        groupedByDate[debate.date] = [];
      }
      groupedByDate[debate.date].push(debate);
    }

    // Calculate daily stats
    const dailyStats = Object.entries(groupedByDate)
      .map(([date, dayDebates]) => ({
        date,
        debateCount: dayDebates.length,
        totalVotes: dayDebates.reduce((sum, d) => sum + d.agreeCount + d.disagreeCount + d.neutralCount, 0),
        totalComments: dayDebates.reduce((sum, d) => sum + d.commentCount, 0),
        topDebate: dayDebates.sort((a, b) => 
          (b.agreeCount + b.disagreeCount + b.neutralCount + b.commentCount) - 
          (a.agreeCount + a.disagreeCount + a.neutralCount + a.commentCount)
        )[0],
        debates: dayDebates.sort((a, b) => a.slot - b.slot),
      }))
      .sort((a, b) => b.date.localeCompare(a.date))
      .slice(0, limit);

    return {
      archives: dailyStats,
      totalDays: dailyStats.length,
      dateRange: {
        start: dailyStats[dailyStats.length - 1]?.date || today,
        end: dailyStats[0]?.date || today,
      },
    };
  },
});

/**
 * Get detailed debate with all votes and comments (for admin)
 */
export const getDebateDetails = query({
  args: { debateId: v.id("dailyDebates") },
  handler: async (ctx, args) => {
    const debate = await ctx.db.get(args.debateId);
    if (!debate) return null;

    // Get all votes with voter info
    const votes = await ctx.db
      .query("debateVotes")
      .withIndex("by_debate", (q) => q.eq("debateId", args.debateId))
      .collect();

    const enrichedVotes = await Promise.all(
      votes.map(async (vote) => {
        let voterInfo = { name: "Anonymous", flag: "🌍" };
        
        if (vote.voterType === "member" && vote.memberId) {
          const member = await ctx.db.get(vote.memberId);
          if (member) {
            voterInfo = { name: member.name, flag: "" };
          }
        } else if (vote.anonymousId) {
          const anon = await ctx.db.get(vote.anonymousId);
          if (anon) {
            voterInfo = { name: anon.pseudonym, flag: anon.countryFlag };
          }
        }

        return {
          ...vote,
          voterInfo,
          timestamp: vote.timestamp,
        };
      })
    );

    // Get all comments with author info
    const comments = await ctx.db
      .query("debateComments")
      .withIndex("by_debate", (q) => q.eq("debateId", args.debateId))
      .collect();

    const enrichedComments = await Promise.all(
      comments.map(async (comment) => {
        let authorInfo = { name: "Anonymous", flag: "🌍", badge: null as string | null };
        
        if (comment.authorType === "member" && comment.memberId) {
          const member = await ctx.db.get(comment.memberId);
          if (member) {
            authorInfo = { 
              name: member.name, 
              flag: "", 
              badge: member.isPremium ? "premium" : null 
            };
          }
        } else if (comment.anonymousId) {
          const anon = await ctx.db.get(comment.anonymousId);
          if (anon) {
            authorInfo = { name: anon.pseudonym, flag: anon.countryFlag, badge: null };
          }
        }

        return {
          ...comment,
          authorInfo,
        };
      })
    );

    return {
      debate,
      votes: enrichedVotes.sort((a, b) => b.timestamp - a.timestamp),
      comments: enrichedComments.sort((a, b) => (b._creationTime || 0) - (a._creationTime || 0)),
      stats: {
        totalVotes: votes.length,
        memberVotes: votes.filter(v => v.voterType === "member").length,
        anonymousVotes: votes.filter(v => v.voterType === "anonymous").length,
        totalComments: comments.length,
        memberComments: comments.filter(c => c.authorType === "member").length,
        anonymousComments: comments.filter(c => c.authorType === "anonymous").length,
      },
    };
  },
});

/**
 * Export debate data for archiving (admin only)
 */
export const exportDebateData = query({
  args: { date: v.string() },
  handler: async (ctx, args) => {
    const debates = await ctx.db
      .query("dailyDebates")
      .withIndex("by_date", (q) => q.eq("date", args.date))
      .collect();

    const fullData = await Promise.all(
      debates.map(async (debate) => {
        const votes = await ctx.db
          .query("debateVotes")
          .withIndex("by_debate", (q) => q.eq("debateId", debate._id))
          .collect();

        const comments = await ctx.db
          .query("debateComments")
          .withIndex("by_debate", (q) => q.eq("debateId", debate._id))
          .collect();

        return {
          debate,
          votes,
          comments,
        };
      })
    );

    return {
      date: args.date,
      exportedAt: new Date().toISOString(),
      data: fullData,
    };
  },
});
