import { mutation } from "./_generated/server";

export const seedGlobalResources = mutation({
  handler: async (ctx) => {
    // Delete existing resources to reseed with comprehensive data
    const existing = await ctx.db.query("safetyResources").collect();
    for (const resource of existing) {
      await ctx.db.delete(resource._id);
    }

    const resources = [
      // ============ GLOBAL RESOURCES ============
      {
        name: "Lila.help - Global Women's Shelter Directory",
        category: "shelter" as const,
        description: "Global directory connecting women to vetted shelters, helplines, and crisis centers worldwide. Features safety exit button.",
        website: "https://www.lila.help/",
        isGlobal: true,
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Shelter Locator", "Crisis Centers", "Helplines"],
        languages: ["Multiple Languages"],
      },
      {
        name: "Hot Peach Pages",
        category: "hotline" as const,
        description: "Searchable list of abuse hotlines, shelters, and crisis centers for every country. Information in 110+ languages.",
        website: "https://www.hotpeachpages.net/",
        isGlobal: true,
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Hotline Directory", "Shelter Locator", "Multilingual Support"],
        languages: ["110+ Languages"],
      },
      {
        name: "NO MORE Global Directory",
        category: "community" as const,
        description: "Created with UN and World Bank. Comprehensive hub for domestic violence resources in almost every UN-recognized country.",
        website: "https://nomoredirectory.org/",
        isGlobal: true,
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Resource Directory", "Crisis Support", "Policy Information"],
      },
      {
        name: "Global Network of Women's Shelters (GNWS)",
        category: "shelter" as const,
        description: "Primary unifying body for women's shelter movement globally. Promotes social change to end violence against women.",
        website: "https://gnws.org/",
        isGlobal: true,
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Shelter Network", "Advocacy", "Training"],
      },
      {
        name: "Global Survivor Network",
        category: "community" as const,
        description: "Connects survivors of trafficking and violence across countries to lead advocacy efforts.",
        website: "https://www.yoursite.org/",
        isGlobal: true,
        isVerified: true,
        isActive: true,
        priority: 3,
        services: ["Peer Support", "Advocacy", "Leadership Training"],
      },

      // ============ UNITED STATES ============
      {
        name: "National Domestic Violence Hotline",
        category: "hotline" as const,
        description: "24/7 confidential support for domestic violence survivors. Advocates available in 200+ languages via interpreters.",
        phone: "1-800-799-7233",
        website: "https://www.thehotline.org/",
        country: "United States",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Safety Planning", "Shelter Referrals", "Legal Advocacy"],
        hours: "24/7",
        languages: ["English", "Spanish", "200+ via interpreters"],
      },
      {
        name: "RAINN - National Sexual Assault Hotline",
        category: "hotline" as const,
        description: "Nation's largest anti-sexual violence organization. Free, confidential 24/7 support.",
        phone: "1-800-656-4673",
        website: "https://www.rainn.org/",
        country: "United States",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Sexual Assault Support", "Counseling", "Legal Resources"],
        hours: "24/7",
        languages: ["English", "Spanish"],
      },
      {
        name: "Love Is Respect - Teen Dating Abuse",
        category: "hotline" as const,
        description: "Targeted support for adolescents experiencing dating violence.",
        phone: "1-866-331-9474",
        website: "https://www.loveisrespect.org/",
        country: "United States",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Teen Support", "Dating Violence Help", "Text Support"],
        hours: "24/7",
      },
      {
        name: "StrongHearts Native Helpline",
        category: "hotline" as const,
        description: "Culturally-appropriate support for Native Americans affected by domestic and sexual violence.",
        phone: "1-844-762-8483",
        website: "https://strongheartshelpline.org/",
        country: "United States",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Cultural Resources", "Tribal Advocacy"],
        hours: "24/7",
      },
      {
        name: "WomensLaw.org",
        category: "legal" as const,
        description: "State-by-state legal directory with plain-language explanations of protection orders, custody, and immigration relief.",
        website: "https://www.womenslaw.org/",
        country: "United States",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Legal Information", "State Laws", "Email Hotline"],
      },
      {
        name: "Her Justice",
        category: "legal" as const,
        description: "Pro bono legal services for women in NYC. Addresses family, matrimonial, and immigration law.",
        website: "https://herjustice.org/",
        country: "United States",
        city: "New York",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Pro Bono Legal Aid", "Immigration", "Family Law"],
      },
      {
        name: "Women's Independence Scholarship Program (WISP)",
        category: "education" as const,
        description: "Grants up to $6,000 for survivors of intimate partner abuse to access higher education.",
        website: "https://wispinc.org/",
        country: "United States",
        isVerified: true,
        isActive: true,
        priority: 3,
        services: ["Scholarships", "Education Support", "Financial Aid"],
      },
      {
        name: "Sanctuary for Families",
        category: "employment" as const,
        description: "Economic Empowerment Program with career readiness workshops and IT training for living-wage employment.",
        website: "https://sanctuaryforfamilies.org/",
        country: "United States",
        city: "New York",
        isVerified: true,
        isActive: true,
        priority: 3,
        services: ["Job Training", "Career Counseling", "IT Skills"],
      },

      // ============ CANADA ============
      {
        name: "ShelterSafe Canada",
        category: "shelter" as const,
        description: "Centralized clickable map connecting women to nearest shelter. 24/7 crisis counseling and safety planning.",
        website: "https://sheltersafe.ca/",
        country: "Canada",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Shelter Locator", "Crisis Counseling", "Safety Planning"],
        hours: "24/7",
      },
      {
        name: "Assaulted Women's Helpline",
        category: "hotline" as const,
        description: "24-hour crisis line for women who have experienced abuse in Ontario.",
        phone: "1-866-863-0511",
        website: "https://www.awhl.org/",
        country: "Canada",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Safety Planning", "Referrals"],
        hours: "24/7",
        languages: ["English", "200+ via interpreters"],
      },
      {
        name: "EASE - Economic Abuse Support Empowerment",
        category: "financial" as const,
        description: "Collaborates with financial institutions to repair credit scores and financial health of survivors.",
        website: "https://womanact.ca/",
        country: "Canada",
        isVerified: true,
        isActive: true,
        priority: 3,
        services: ["Financial Recovery", "Credit Repair", "Banking Support"],
      },

      // ============ UNITED KINGDOM ============
      {
        name: "National Domestic Abuse Helpline (Refuge)",
        category: "hotline" as const,
        description: "Run by Refuge. Free, confidential 24-hour support for women experiencing domestic abuse.",
        phone: "0808 2000 247",
        website: "https://www.nationaldahelpline.org.uk/",
        country: "United Kingdom",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Safety Planning", "Refuge Referrals"],
        hours: "24/7",
        languages: ["English", "Interpreters available"],
      },
      {
        name: "Women's Aid UK",
        category: "shelter" as const,
        description: "National charity with up-to-date database of local services including Rail to Refuge travel schemes.",
        website: "https://www.womensaid.org.uk/",
        country: "United Kingdom",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Shelter Directory", "Legal Support", "Children's Services"],
      },
      {
        name: "Galop - LGBT+ Support",
        category: "counseling" as const,
        description: "Specialist support for LGBT+ survivors of domestic abuse and hate crime.",
        website: "https://galop.org.uk/",
        country: "United Kingdom",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["LGBT+ Support", "Hate Crime", "Domestic Abuse"],
      },
      {
        name: "Surviving Economic Abuse (SEA)",
        category: "financial" as const,
        description: "Provides grants to pay off coerced debt and stabilize housing for survivors.",
        website: "https://survivingeconomicabuse.org/",
        country: "United Kingdom",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Debt Relief", "Financial Grants", "Housing Support"],
      },
      {
        name: "The Survivors Trust",
        category: "counseling" as const,
        description: "Umbrella agency for 120+ organizations providing specialist support for rape and sexual violence survivors.",
        website: "https://www.thesurvivorstrust.org/",
        country: "United Kingdom",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Counseling Network", "Specialist Support", "Referrals"],
      },

      // ============ MEXICO ============
      {
        name: "Red Nacional de Refugios",
        category: "shelter" as const,
        description: "National Network of Shelters providing protection, medical care, and psychological support.",
        phone: "55 5674 9695",
        website: "https://rednacionalderefugios.org.mx/",
        country: "Mexico",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Shelter", "Medical Care", "Psychological Support"],
        hours: "24/7",
        languages: ["Spanish"],
      },
      {
        name: "SAPTEL - Cruz Roja",
        category: "counseling" as const,
        description: "24/7 psychological crisis intervention hotline operated by Red Cross.",
        phone: "55 5259 8121",
        country: "Mexico",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Intervention", "Psychological Support"],
        hours: "24/7",
        languages: ["Spanish"],
      },
      {
        name: "Consejo Ciudadano",
        category: "legal" as const,
        description: "Legal and psychological advice for women in Mexico.",
        phone: "55 5533 5533",
        country: "Mexico",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Legal Advice", "Psychological Support"],
        hours: "24/7",
        languages: ["Spanish"],
      },

      // ============ COLOMBIA ============
      {
        name: "Línea 155",
        category: "hotline" as const,
        description: "National orientation line for domestic violence. Legal advice and psychological support under Ley 1257.",
        phone: "155",
        country: "Colombia",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Legal Advice", "Psychological Support", "Rights Information"],
        hours: "24/7",
        languages: ["Spanish"],
      },
      {
        name: "Línea Púrpura Bogotá",
        category: "hotline" as const,
        description: "Specialized toll-free line with psychologists and lawyers. WhatsApp with sign language interpretation.",
        phone: "01 8000 112 137",
        country: "Colombia",
        city: "Bogotá",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Legal Aid", "Psychological Support", "Sign Language"],
        hours: "24/7",
        languages: ["Spanish", "Sign Language"],
      },
      {
        name: "Fundación Ana Bella Colombia",
        category: "community" as const,
        description: "Support networks using peer-to-peer mentoring to help women exit abusive relationships.",
        website: "https://fundacionanabella.org/",
        country: "Colombia",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Peer Support", "Mentoring", "Employment"],
      },

      // ============ ARGENTINA ============
      {
        name: "Línea 144",
        category: "hotline" as const,
        description: "Omni-channel platform via phone, WhatsApp, email, and mobile app. Advice and referrals nationwide.",
        phone: "144",
        website: "https://www.argentina.gob.ar/generos/linea-144",
        country: "Argentina",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Referrals", "WhatsApp Support"],
        hours: "24/7",
        languages: ["Spanish"],
      },

      // ============ PERU ============
      {
        name: "Centros de Emergencia Mujer (CEM)",
        category: "shelter" as const,
        description: "Multidisciplinary centers providing legal, psychological, and social support. Many located in police stations.",
        website: "https://www.mimp.gob.pe/",
        country: "Peru",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Legal Aid", "Psychological Support", "Social Services"],
        languages: ["Spanish", "Quechua"],
      },

      // ============ INDIA ============
      {
        name: "Women Helpline 181",
        category: "hotline" as const,
        description: "Universal toll-free number for women in distress, integrated with police and hospital services.",
        phone: "181",
        country: "India",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Emergency Response", "Police Assistance", "Hospital Referrals"],
        hours: "24/7",
        languages: ["Hindi", "English", "Regional Languages"],
      },
      {
        name: "Sakhi One Stop Centres",
        category: "shelter" as const,
        description: "Integrated support centers providing medical, legal, psychological, and shelter services under one roof.",
        website: "http://www.wcd.nic.in/",
        country: "India",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Medical", "Legal", "Psychological", "Shelter"],
        hours: "24/7",
      },
      {
        name: "KIRAN Mental Health Helpline",
        category: "counseling" as const,
        description: "Free mental health helpline addressing psychological aftermath of abuse.",
        phone: "1800-599-0019",
        country: "India",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Mental Health", "Crisis Counseling", "Referrals"],
        hours: "24/7",
        languages: ["Hindi", "English"],
      },
      {
        name: "National Commission for Women",
        category: "legal" as const,
        description: "Statutory body for safeguarding women's rights. Handles complaints and policy advocacy.",
        phone: "7827-170-170",
        website: "http://ncw.nic.in/",
        country: "India",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Legal Aid", "Complaints", "Policy Advocacy"],
      },
      {
        name: "SEWA - Self Employed Women's Association",
        category: "employment" as const,
        description: "Trade union and support network empowering women in informal economy through collective bargaining.",
        website: "https://www.sewa.org/",
        country: "India",
        isVerified: true,
        isActive: true,
        priority: 3,
        services: ["Employment", "Financial Services", "Collective Bargaining"],
      },

      // ============ SOUTH AFRICA ============
      {
        name: "Gender-Based Violence Command Centre",
        category: "hotline" as const,
        description: "24/7 call center with social workers. Uses geolocation to dispatch police or ambulances.",
        phone: "0800 428 428",
        country: "South Africa",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Response", "Police Dispatch", "Ambulance"],
        hours: "24/7",
      },
      {
        name: "Thuthuzela Care Centres",
        category: "medical" as const,
        description: "One-stop facilities at hospitals integrating medical examination, police reporting, and prosecution services.",
        country: "South Africa",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Medical Care", "Police Reporting", "Legal Support"],
        hours: "24/7",
      },
      {
        name: "POWA - People Opposing Women Abuse",
        category: "shelter" as const,
        description: "Provides shelters and counseling for women experiencing abuse.",
        website: "https://www.powa.co.za/",
        country: "South Africa",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Shelter", "Counseling", "Legal Aid"],
      },

      // ============ NIGERIA ============
      {
        name: "WARDC - Women Advocates Research and Documentation Centre",
        category: "legal" as const,
        description: "Pro bono legal aid and shelters for victims of gender-based violence.",
        website: "https://www.wardcnigeria.org/",
        country: "Nigeria",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Pro Bono Legal Aid", "Shelter", "Advocacy"],
      },
      {
        name: "Eko Haven Lagos",
        category: "shelter" as const,
        description: "30-bed capacity shelter in Ikorodu helping high-risk survivors.",
        country: "Nigeria",
        city: "Lagos",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Emergency Shelter", "Rehabilitation"],
      },

      // ============ KENYA ============
      {
        name: "FIDA Kenya",
        category: "legal" as const,
        description: "Federation of Women Lawyers offering free legal aid in custody, inheritance, and violence matters.",
        phone: "+254 20 2604044",
        website: "https://fidakenya.org/",
        country: "Kenya",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Free Legal Aid", "Custody", "Inheritance", "Violence Cases"],
      },

      // ============ AUSTRALIA ============
      {
        name: "1800RESPECT",
        category: "hotline" as const,
        description: "National sexual assault, domestic and family violence counselling service.",
        phone: "1800 737 732",
        website: "https://www.1800respect.org.au/",
        country: "Australia",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Counseling", "Crisis Support", "Referrals"],
        hours: "24/7",
        languages: ["English", "Interpreters available"],
      },
      {
        name: "Women Talk Money (WIRE)",
        category: "financial" as const,
        description: "Financial coaching focusing on financial independence as a safety strategy against economic abuse.",
        website: "https://www.wire.org.au/",
        country: "Australia",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Financial Coaching", "Economic Abuse Support"],
      },

      // ============ SOUTH KOREA ============
      {
        name: "Women's Emergency Hotline 1366",
        category: "hotline" as const,
        description: "24/7 crisis counseling and shelter referral for women.",
        phone: "1366",
        country: "South Korea",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Counseling", "Shelter Referral"],
        hours: "24/7",
        languages: ["Korean", "English"],
      },
      {
        name: "Korea Sexual Violence Relief Center",
        category: "counseling" as const,
        description: "Feminist advocacy and specialized legal support for sexual violence survivors.",
        website: "https://www.sisters.or.kr/",
        country: "South Korea",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Legal Support", "Counseling", "Advocacy"],
      },

      // ============ JAPAN ============
      {
        name: "Spousal Violence Counseling Centers",
        category: "counseling" as const,
        description: "Government counseling centers accessible via shortened dial #8008.",
        phone: "#8008",
        country: "Japan",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Counseling", "Shelter Referrals"],
        languages: ["Japanese"],
      },
      {
        name: "TELL Japan",
        category: "counseling" as const,
        description: "English-language mental health support and counseling for international community.",
        phone: "03-5774-0992",
        website: "https://telljp.com/",
        country: "Japan",
        isVerified: true,
        isActive: true,
        priority: 2,
        services: ["Mental Health", "English Support", "Counseling"],
        languages: ["English", "Japanese"],
      },

      // ============ EUROPEAN HOTLINES (WAVE Network) ============
      {
        name: "Frauenhelpline gegen Gewalt (Austria)",
        category: "hotline" as const,
        description: "Austrian women's helpline against violence.",
        phone: "0800 222 555",
        country: "Austria",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Counseling"],
        hours: "24/7",
        languages: ["German"],
      },
      {
        name: "Écoute Violences Conjugales (Belgium)",
        category: "hotline" as const,
        description: "Belgian domestic violence helpline.",
        phone: "0800 30 030",
        country: "Belgium",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Counseling"],
        hours: "24/7",
        languages: ["French", "Dutch"],
      },
      {
        name: "Kvinnofridslinjen (Sweden)",
        category: "hotline" as const,
        description: "Swedish national women's helpline.",
        phone: "116 016",
        country: "Sweden",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Counseling"],
        hours: "24/7",
        languages: ["Swedish", "English"],
      },
      {
        name: "Línea 016 (Spain)",
        category: "hotline" as const,
        description: "Spanish GBV helpline. Leaves no trace on phone bills for safety.",
        phone: "016",
        country: "Spain",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Legal Information"],
        hours: "24/7",
        languages: ["Spanish"],
      },
      {
        name: "Antiviolenza e Stalking 1522 (Italy)",
        category: "hotline" as const,
        description: "Italian anti-violence and stalking helpline.",
        phone: "1522",
        country: "Italy",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Stalking Help"],
        hours: "24/7",
        languages: ["Italian"],
      },
      {
        name: "Niebieska Linia - Blue Line (Poland)",
        category: "hotline" as const,
        description: "Historic Polish service for victims of domestic violence.",
        phone: "800 120 002",
        country: "Poland",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Counseling"],
        hours: "24/7",
        languages: ["Polish"],
      },

      // ============ PHILIPPINES ============
      {
        name: "Recovery and Reintegration Program for Trafficked Persons",
        category: "shelter" as const,
        description: "Comprehensive recovery packages including shelter and capital assistance for trafficking victims.",
        country: "Philippines",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Shelter", "Recovery", "Capital Assistance"],
      },

      // ============ CHILE ============
      {
        name: "SernamEG Helpline",
        category: "hotline" as const,
        description: "National Service for Women and Gender Equity helpline.",
        phone: "1455",
        country: "Chile",
        isVerified: true,
        isActive: true,
        priority: 1,
        services: ["Crisis Support", "Legal Information"],
        hours: "24/7",
        languages: ["Spanish"],
      },
    ];

    for (const resource of resources) {
      await ctx.db.insert("safetyResources", {
        ...resource,
        verificationCount: 10,
      });
    }

    return { message: `Seeded ${resources.length} comprehensive global resources` };
  },
});
